version: "3"

services:
  backend:
    build: ./backend
    image: ci-cd-website-backend  
    ports:
      - "3000:3000"
  
  frontend:
    build: ./frontend
    image: ci-cd-website-frontend  
    ports:
      - "8081:80"
